### ISSUE TITLE
Add type = module to the .info file

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/menu_trail_by_path#1]
When I try to install *Menu Trail By Path* on a Backdrop 1.7.0 site, I get the message `The info file (.../menu_trail_by_path-1.x-1.x/menu_trail_by_path.info) does not define a 'type' attribute`, and I can't continue with the installation.

To fix the issue, please add

`type = module`

to the `.info` file.

**Comment by klonos** [comment]
PR: https://github.com/backdrop-contrib/menu_trail_by_path/pull/2

**Comment by olafgrabienski** [comment]
Thanks @klonos, looks good to me!
